# Generated by Django 2.2.6 on 2019-10-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191016_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.AddField(
            model_name='profile',
            name='problems_solvd',
            field=models.IntegerField(default=0),
        ),
    ]
