# Generated by Django 2.2.6 on 2019-10-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('users', '0003_auto_20191016_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='questions_solved',
            field=models.ManyToManyField(blank=True, null=True, to='questions.Question'),
        ),
    ]
