# Generated by Django 2.2.6 on 2019-10-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_questions_solved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('question_solvd_to_get', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='questions_solved',
            field=models.ManyToManyField(to='questions.Question'),
        ),
        migrations.AddField(
            model_name='profile',
            name='achivements',
            field=models.ManyToManyField(to='users.Achievement'),
        ),
    ]
